# Generated by Django 5.1.6 on 2025-11-06 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-11-06 07:32:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topics/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='page_content',
            field=models.TextField(blank=True, verbose_name='HTML контент'),
        ),
        migrations.AddField(
            model_name='topic',
            name='page_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON с уникальными данными для этой страницы', verbose_name='Данные страницы'),
        ),
        migrations.AddField(
            model_name='topic',
            name='short_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='topic',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.category'),
        ),
    ]
