# Generated by Django 5.1.6 on 2025-11-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_topic_content_topic_created_at_topic_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='complexity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='earning_opportunity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='initial_investment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='online',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='relevance',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='risks',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='time_required',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
